;//Alias header file for CHM project
;//Automatically generated by Easy CHM.
;//Website : http://www.zipghost.com
;//Email   : webmaster@zipghost.com
;//Date    : 2013/4/24 1:03:46

;//NOTE:
;//All strings after the ";" are commnets, they will be ignored by the CHM Compiler.

IDH_1001=index.html	; Index
IDH_1002=readme_BJ Editor.html	; - BJ Editor
IDH_1004=readme_UniStringTransferTool.html	; - Uni-String Transfer Tool
IDH_1003=readme_PackMPQ.html	; - PackMPQ
IDH_1000=about.html	; About
