;//Map header file for CHM project
;//Automatically generated by Easy CHM.
;//Website : http://www.zipghost.com
;//Email   : webmaster@zipghost.com
;//Date    : 2013/4/24 1:03:46

;//NOTE:
;//All strings after the ";" are commnets, they will be ignored by the CHM Compiler.

#define IDH_1001	1001	; Index index.html
#define IDH_1002	1002	; - BJ Editor readme_BJ Editor.html
#define IDH_1004	1004	; - Uni-String Transfer Tool readme_UniStringTransferTool.html
#define IDH_1003	1003	; - PackMPQ readme_PackMPQ.html
#define IDH_1000	1000	; About about.html
